### ISSUE TITLE
ModuleNotFoundError: No module named 'rl'

### ISSUE THREAD

**Issue by huanghub6224** [RealVNF/DeepCoord#1]
Hi, thanks for your contributions! that's really helpful.
I run the src/rlsp/agents/main.py at Pycharm
but an error occurre：
Traceback (most recent call last):
  File "D:/Deep reinforcement learning programming/DeepCoord-master/src/rlsp/agents/main.py", line 14, in <module>
    from rlsp.agents.rlsp_ddpg import DDPG
  File "D:\Deep reinforcement learning programming\DeepCoord-master\src\rlsp\agents\rlsp_ddpg.py", line 5, in <module>
    from rl.agents import DDPGAgent
ModuleNotFoundError: No module named 'rl'

I searched for a long time and didn't find where and what ‘rl’ module is
so How can I solve this problem？ thank you!

**Comment by qarawlus** [comment]
Hello,

Did you already install the required dependencies (https://github.com/RealVNF/DeepCoord#setup)?. The error looks like a missing dependency problem. 

This should take care of the missing module error.
