### ISSUE TITLE
ValueError:  when use '--weight' to continue to train the SAC agent

### ISSUE THREAD

**Issue by huanghub6224** [RealVNF/DeepCoord#9]
Hello, Stefan and co-authors, how is it going. Thank you for your help earlier, our paper has been submitted and entered the second trial stage. We also cited your work in the submitted paper. At present, we have encountered a new problem, when using the '--weight'  command to continue to train the SAC agent, an error occurred as below.

We run the code on pycharm and mapping it to the remote GPU server at '/tmp/pycharm_project_264', note that, '2022-06-04_20-00-56_seed2826' is the  folder where the previous training parameters are stored, we want to reuse these parameters to continue train the SAC agent.  and here is the details error:

Traceback (most recent call last):
  File "/tmp/pycharm_project_264/src/rlsp/agents/main.py", line 520, in <module>
    cli([agent_config, network, service, sim_config, '100', '--append-test', '--weights', '2022-06-04_20-00-56_seed2826'])  
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/pycharm_project_264/src/rlsp/agents/main.py", line 66, in cli
    execute(agent_helper)
  File "/tmp/pycharm_project_264/src/rlsp/agents/main.py", line 130, in execute
    train_agent(agent_helper)
  File "/tmp/pycharm_project_264/src/rlsp/agents/main.py", line 151, in train_agent
    training(agent_helper.agent, agent_helper.env, agent_helper.callbacks, agent_helper.episodes, agent_helper.result)
  File "/tmp/pycharm_project_264/src/rlsp/agents/main.py", line 398, in training
    log_interval=episodes * episode_steps)
  File "/tmp/pycharm_project_264/src/rlsp/agents/rlsp_sac.py", line 51, in fit
    self.agent.learn(steps, callback=self._callbacks, tb_log_name=self.agent_helper.graph_path)
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines/sac/sac.py", line 366, in learn
    self._setup_learn()
  File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/base_class.py", line 225, in _setup_learn
    raise ValueError("Error: cannot train the model without a valid environment, please set an environment with"
ValueError: Error: cannot train the model without a valid environment, please set an environment withset_env(self, env) method.

1. I googled the error but still couldn't find a good solution.
2. This seems to be due to the env not being set up, but we redefine the env and it still doesn't work?
3. We used the rlsp_sac.py you sent me previously as the configuration file of SAC agent, and noticed that the parameters file saved by SAC is 'weights.zip', while the parameters files saved by DDPG are 'weight_actor.h5f' and 'weight_critic.h5f'. Is it because of inconsistent formats? 
4. other commands '--test', '-gs', '--append-test' of SAC training and testing all can be run successfully.
6. Looking forward to your reply, and this is my email if needed, jonwong.must@gmail.com. please feel free to contact me.

**Comment by stefanbschneider** [comment]
Hi Jon, thanks for reaching out and for citing our paper! We didn't work with SAC too much so it might be some issue with the weights format that we did not notice; I don't know what it is from the top of my head.
I'm very busy at the moment but will try to look into it when I have some time. If you resolve the issue yourself, it would be great if you could post the solution - maybe even a PR :)

**Comment by huanghub6224** [comment]
OK, I'll do my best, and I'll let you know as there is progress.

**Comment by huanghub6224** [comment]
hello, Stefan, I just solved that problem! 
First, I changed the save format of SAC to the same format as DDPG, i.e, h5f,  but it still doesn't work;
Then, I Google the error and find it from stable_baseline's  environment checking in learn function:
        """
        Check the environment.
        """
        if self.env is None:
            raise ValueError("Error: cannot train the model without a valid environment, please set an environment with"
                             "set_env(self, env) method.")

So I redefined the "self.agent.env  = env"  in rlsp_sac.py:

    def fit(self, env, episodes, verbose, episode_steps, callbacks, log_interval):
        """Mask the agent fit function"""
        steps = episodes * self.agent_helper.episode_steps 
        self.agent.env = env   ##added command
        self.agent.learn(steps, callback=self._callbacks, tb_log_name=self.agent_helper.graph_path)
        self.close_callbacks()

and it works!

**Comment by stefanbschneider** [comment]
Great, thanks for solving this and posting the solution!

Would you mind opening a pull request with the change? Would be a great contribution to DeepCoord :)

**Comment by huanghub6224** [comment]
hello, Stefan, sorry for the slow reply, I have opened a new pull request that updates the rlsp_sac.py  file, please check it and have a good day.

**Comment by stefanbschneider** [comment]
Thank you @huanghub6224 !
